package com.docuexec.commutingservices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class entity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer distance;
	private java.lang.Integer vehicleType;
	private java.lang.Double discount;
	private java.lang.Double totalFare;
	private java.lang.Double pricePerKm;

	public entity() {
	}

	public java.lang.Integer getDistance() {
		return this.distance;
	}

	public void setDistance(java.lang.Integer distance) {
		this.distance = distance;
	}

	public java.lang.Integer getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(java.lang.Integer vehicleType) {
		this.vehicleType = vehicleType;
	}

	public java.lang.Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Double discount) {
		this.discount = discount;
	}

	public java.lang.Double getTotalFare() {
		return this.totalFare;
	}

	public void setTotalFare(java.lang.Double totalFare) {
		this.totalFare = totalFare;
	}

	public java.lang.Double getPricePerKm() {
		return this.pricePerKm;
	}

	public void setPricePerKm(java.lang.Double pricePerKm) {
		this.pricePerKm = pricePerKm;
	}

	public entity(java.lang.Integer distance, java.lang.Integer vehicleType,
			java.lang.Double discount, java.lang.Double totalFare,
			java.lang.Double pricePerKm) {
		this.distance = distance;
		this.vehicleType = vehicleType;
		this.discount = discount;
		this.totalFare = totalFare;
		this.pricePerKm = pricePerKm;
	}

}